# Generated by Django 4.1.3 on 2022-11-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dose', models.CharField(max_length=1)),
                ('pesticide', models.CharField(choices=[('F', 'Fungicide'), ('I', 'Insecticide'), ('H', 'Herbicide')], default=('F', 'Fungicide'), max_length=100)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
        ),
    ]
