# Generated by Django 4.1.3 on 2022-11-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_debug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lumen', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='debug',
            name='date',
            field=models.DateField(verbose_name='debug date'),
        ),
        migrations.AlterField(
            model_name='debug',
            name='pesticide',
            field=models.CharField(choices=[('F', 'Fungicide'), ('I', 'Insecticide'), ('H', 'Herbicide')], default=('F', 'Fungicide'), max_length=1),
        ),
        migrations.AddField(
            model_name='plant',
            name='light',
            field=models.ManyToManyField(to='main_app.light'),
        ),
    ]
