# Generated by Django 4.1.3 on 2022-11-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_light_alter_debug_date_alter_debug_pesticide_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='light',
            new_name='lights',
        ),
    ]
